'use strict';

/**
 * E2E tests for /api/orders
 *
 * Routes:
 *   GET  /                          - list (orders:list)
 *   GET  /get                       - single (orders:get)
 *   POST /add                       - create (orders:add)
 *   POST /edit                      - update (orders:edit)
 *   POST /delete                    - delete (orders:delete)
 *   POST /:id/status/update         - change status (orders:status_update)
 *   POST /:id/payment_status/update - change payment status (orders:payment_status_update)
 *   GET  /:id/invoice/download      - download PDF invoice (guest allowed)
 *   POST /:id/message/add           - add message (orders:message_add)
 *   GET  /messages/list             - list order messages (orders:messages_list)
 *   POST /export                    - export to CSV/Excel (orders:export)
 */

const { getRequest } = require('./helpers/testApp');
const { authAs }     = require('./helpers/auth');

let request;
let seeds;

beforeAll(() => {
  seeds   = global.__TEST_SEEDS__;
  request = getRequest();
});

function expectSuccess(res, statusCode = 200) {
  expect(res.status).toBe(statusCode);
  expect(res.body).toHaveProperty('ts');
  expect(res.body).toHaveProperty('result');
}

function expectError(res, statusCode) {
  expect(res.status).toBe(statusCode);
  expect(res.body).toHaveProperty('error');
}

// ---------------------------------------------------------------------------
// GET /api/orders — list
// ---------------------------------------------------------------------------

describe('GET /api/orders (orders:list)', () => {
  it('admin can list all orders', async () => {
    const res = await request.get('/api/orders').set(authAs('admin'));

    expectSuccess(res);
    // orders list returns { data: [...], count: N }
    expect(Array.isArray(res.body.result.data)).toBe(true);
  });

  it('client can only see own orders', async () => {
    const res = await request.get('/api/orders').set(authAs('client'));

    expectSuccess(res);
    expect(Array.isArray(res.body.result.data)).toBe(true);
    res.body.result.data.forEach(order => {
      expect(order.UserId).toBe(seeds.userIds.client);
    });
  });

  it('returns 401 without auth', async () => {
    const res = await request.get('/api/orders');
    expectError(res, 401);
  });

  it('supports pagination', async () => {
    const res = await request
      .get('/api/orders')
      .query({ limit: 1, offset: 0 })
      .set(authAs('admin'));

    expectSuccess(res);
    expect(res.body.result.data.length).toBeLessThanOrEqual(1);
  });

  it('filters by orderStatus', async () => {
    const where = JSON.stringify({ orderStatus: ['pending'] });
    const res = await request
      .get('/api/orders')
      .query({ where })
      .set(authAs('admin'));

    expectSuccess(res);
    res.body.result.data.forEach(order => {
      expect(order.orderStatus).toBe('pending');
    });
  });

  it('filters by paymentStatus', async () => {
    const where = JSON.stringify({ paymentStatus: ['pending'] });
    const res = await request
      .get('/api/orders')
      .query({ where })
      .set(authAs('admin'));

    expectSuccess(res);
    res.body.result.data.forEach(order => {
      expect(order.paymentStatus).toBe('pending');
    });
  });

  it('filters by countryCodeFrom', async () => {
    const where = JSON.stringify({ countryCodeFrom: 'RU' });
    const res = await request
      .get('/api/orders')
      .query({ where })
      .set(authAs('admin'));

    expectSuccess(res);
    res.body.result.data.forEach(order => {
      expect(order.countryCodeFrom).toBe('RU');
    });
  });

  it('response includes Carrier and User data', async () => {
    const res = await request.get('/api/orders').set(authAs('admin'));

    expectSuccess(res);
    if (res.body.result.data.length > 0) {
      const order = res.body.result.data[0];
      expect(order).toHaveProperty('Carrier');
      expect(order).toHaveProperty('User');
    }
  });
});

// ---------------------------------------------------------------------------
// GET /api/orders/get — single order
// ---------------------------------------------------------------------------

describe('GET /api/orders/get (orders:get)', () => {
  it('admin can get any order by id', async () => {
    const res = await request
      .get('/api/orders/get')
      .query({ id: seeds.orderId })
      .set(authAs('admin'));

    expectSuccess(res);
    // refNo is auto-generated by the Order afterCreate hook (format: YYMMDD-NNNNNC)
    expect(res.body.result).toMatchObject({
      id: seeds.orderId,
      orderStatus: 'pending',
    });
  });

  it('client can get their own order', async () => {
    const res = await request
      .get('/api/orders/get')
      .query({ id: seeds.orderId })
      .set(authAs('client'));

    expectSuccess(res);
    expect(res.body.result.id).toBe(seeds.orderId);
  });

  it('response includes Packages', async () => {
    const res = await request
      .get('/api/orders/get')
      .query({ id: seeds.orderId })
      .set(authAs('admin'));

    expectSuccess(res);
    expect(res.body.result).toHaveProperty('Packages');
    expect(Array.isArray(res.body.result.Packages)).toBe(true);
  });

  it('returns 401 without auth', async () => {
    const res = await request
      .get('/api/orders/get')
      .query({ id: seeds.orderId });

    expectError(res, 401);
  });
});

// ---------------------------------------------------------------------------
// POST /api/orders/add — create order
// ---------------------------------------------------------------------------

describe('POST /api/orders/add (orders:add)', () => {
  let createdOrderId;

  const newOrderPayload = () => ({
    UserId: seeds.userIds.admin,  // required NOT NULL FK
    orderStatus: 'pending',
    paymentStatus: 'pending',
    paymentType: 'bankwire',
    declaredValue: 500,
    totalPrice: 300,
    companyPrice: 250,
    clientPrice: 300,
    contents: 'Test package',
    externalComment: 'Test order',
    pickupTime: new Date(Date.now() + 86400000).toISOString(),
    langCode: 'ru',
    countryCodeFrom: 'RU',
    countryCodeTo: 'KZ',
    addressFrom: 'Москва, Тверская 1',
    addressDetailsFrom: {
      city: 'Москва',
      province: '',
      addressLine1: 'Тверская 1',
      phone: '+79001234567',
      email: 'sender@e2e.local',
      firstName: 'Иван',
      lastName: 'Иванов',
      countryCode: 'RU',
    },
    addressTo: 'Алматы, Абая 1',
    addressDetailsTo: {
      city: 'Алматы',
      province: '',
      addressLine1: 'Абая 1',
      phone: '+77771234567',
      email: 'recipient@e2e.local',
      firstName: 'Алибек',
      lastName: 'Алибеков',
      countryCode: 'KZ',
    },
    CarrierId: seeds.carrierId,
    PackageTypeId: seeds.pkgBoxId,
    RateTypeId: seeds.rtStdId,
    Packages: [{ weight: 1, width: 20, height: 20, depth: 20, quantity: 1 }],
    OrderServices: [],
  });

  it('admin can create an order', async () => {
    const res = await request
      .post('/api/orders/add')
      .set(authAs('admin'))
      .send(newOrderPayload());

    expectSuccess(res);
    expect(res.body.result).toHaveProperty('id');
    expect(res.body.result).toHaveProperty('refNo');
    expect(res.body.result.orderStatus).toBe('pending');
    createdOrderId = res.body.result.id;
  });

  it('client can create an order', async () => {
    const res = await request
      .post('/api/orders/add')
      .set(authAs('client'))
      .send({ ...newOrderPayload(), UserId: seeds.userIds.client });

    expect([200, 201, 403]).toContain(res.status);
  });

  afterAll(async () => {
    if (createdOrderId) {
      const models = require('../../models');
      await models.Package.destroy({ where: { OrderId: createdOrderId } });
      await models.Order.destroy({ where: { id: createdOrderId } });
    }
  });
});

// ---------------------------------------------------------------------------
// POST /api/orders/edit — update order
// ---------------------------------------------------------------------------

describe('POST /api/orders/edit (orders:edit)', () => {
  it('admin can edit an order', async () => {
    const res = await request
      .post('/api/orders/edit')
      .set(authAs('admin'))
      .send({
        id: seeds.orderId,
        internalComment: 'Updated by test',
      });

    expectSuccess(res);
    expect(res.body.result.internalComment).toBe('Updated by test');

    // Restore
    await request
      .post('/api/orders/edit')
      .set(authAs('admin'))
      .send({ id: seeds.orderId, internalComment: '' });
  });

  it('returns 401 without auth', async () => {
    const res = await request
      .post('/api/orders/edit')
      .send({ id: seeds.orderId, internalComment: 'X' });

    expectError(res, 401);
  });
});

// ---------------------------------------------------------------------------
// POST /api/orders/delete — delete order
// ---------------------------------------------------------------------------

describe('POST /api/orders/delete (orders:delete)', () => {
  let tempOrderId;

  beforeEach(async () => {
    const models = require('../../models');
    const tempOrder = await models.Order.create({
      refNo: `TEMP-DEL-${Date.now()}`,
      orderStatus: 'pending',
      paymentStatus: 'pending',
      paymentType: 'bankwire',
      declaredValue: 100,
      totalPrice: 100,
      companyPrice: 80,
      clientPrice: 100,
      contents: 'temp',
      pickupTime: new Date(Date.now() + 86400000),
      langCode: 'ru',
      countryCodeFrom: 'RU',
      countryCodeTo: 'KZ',
      addressFrom: 'Test',
      addressDetailsFrom: { city: 'Москва', province: '' },
      addressTo: 'Test',
      addressDetailsTo: { city: 'Алматы', province: '' },
      UserId: seeds.userIds.admin,
      CarrierId: seeds.carrierId,
      PackageTypeId: seeds.pkgBoxId,
      RateTypeId: seeds.rtStdId,
      CompanyId: seeds.companyId,
    });
    tempOrderId = tempOrder.id;
  });

  it('admin can delete an order', async () => {
    const res = await request
      .post('/api/orders/delete')
      .set(authAs('admin'))
      .send({ id: tempOrderId });

    expectSuccess(res);
    // orders/delete route returns true (uses obj.destroy() in a loop, not row count)
    expect(res.body.result).toBe(true);
  });

  it('returns 401 without auth', async () => {
    const res = await request
      .post('/api/orders/delete')
      .send({ id: tempOrderId });

    expectError(res, 401);
  });

  afterEach(async () => {
    const models = require('../../models');
    await models.Order.destroy({ where: { id: tempOrderId }, force: true }).catch(() => {});
  });
});

// ---------------------------------------------------------------------------
// Order status/payment_status update — via POST /api/orders/edit
// NOTE: there is no dedicated /:id/status/update route; status is updated
// through the generic /edit endpoint.
// ---------------------------------------------------------------------------

describe('POST /api/orders/edit — order status update', () => {
  it('admin can change order status via edit endpoint', async () => {
    const res = await request
      .post('/api/orders/edit')
      .set(authAs('admin'))
      .send({ id: seeds.orderId, orderStatus: 'processing' });

    expectSuccess(res);
    expect(res.body.result.orderStatus).toBe('processing');

    // Restore
    await request
      .post('/api/orders/edit')
      .set(authAs('admin'))
      .send({ id: seeds.orderId, orderStatus: 'pending' });
  });

  it('admin can change payment status via edit endpoint', async () => {
    const res = await request
      .post('/api/orders/edit')
      .set(authAs('admin'))
      .send({ id: seeds.orderId, paymentStatus: 'confirmed' });

    expectSuccess(res);
    expect(res.body.result.paymentStatus).toBe('confirmed');

    // Restore
    await request
      .post('/api/orders/edit')
      .set(authAs('admin'))
      .send({ id: seeds.orderId, paymentStatus: 'pending' });
  });

  it('returns 401 without auth', async () => {
    const res = await request
      .post('/api/orders/edit')
      .send({ id: seeds.orderId, orderStatus: 'confirmed' });

    expectError(res, 401);
  });
});

// ---------------------------------------------------------------------------
// GET /api/orders/:id/invoice/download
// ---------------------------------------------------------------------------

describe('GET /api/orders/:id/invoice/download (orders:invoice_download)', () => {
  it('accessible without auth (guest permission)', async () => {
    const res = await request
      .get(`/api/orders/${seeds.orderId}/invoice/download`);

    // Should not be 401 or 403 — may be 200 or 500 (missing PDF dependency)
    expect(res.status).not.toBe(401);
    expect(res.status).not.toBe(403);
  });
});

// ---------------------------------------------------------------------------
// NOTE: The following routes do NOT exist in the current routes/orders.js:
//   GET  /api/orders/messages/list  — orders:messages_list
//   POST /api/orders/:id/message/add — orders:message_add
//   POST /api/orders/export          — orders:export
// Order messages are handled by /api/messages routes instead.
// ---------------------------------------------------------------------------
